trigger:
- main

pool:
  name: 'self-hosted-mac'

variables:
  solution: '*.sln'
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet restore $(solution)
  displayName: 'Restore NuGet packages'

- script: |
    dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build solution'

# - script: |
#     dotnet test $(solution) --configuration $(buildConfiguration) --no-build --verbosity normal
#   displayName: 'Run unit tests'

- script: |
    dotnet publish $(solution) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish solution'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'
