trigger:
- main

pool:
  name: 'self-hosted-mac'

variables:
  solution: '*.sln'
  buildConfiguration: 'Release'
  versionNumber: '1.0.$(Build.BuildId)'

steps:
- script: |
    dotnet restore $(solution)
  displayName: 'Restore NuGet packages'

- script: |
    dotnet build $(solution) --configuration $(buildConfiguration)
  displayName: 'Build solution'

# - script: |
#     dotnet test $(solution) --configuration $(buildConfiguration) --no-build --verbosity normal
#   displayName: 'Run unit tests'

- script: |
    dotnet publish $(solution) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(versionNumber)
  displayName: 'Publish solution'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(versionNumber)'
    ArtifactName: 'drop-$(versionNumber)'
    publishLocation: 'Container'
  displayName: 'Publish build artifacts'

- script: |
    dotnet pack $(solution) --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack solution into NuGet package'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'nuget'
    arguments: 'push $(Build.ArtifactStagingDirectory)/*.nupkg --source "release" --api-key az version1'
  displayName: 'Publish NuGet package to Azure Artifacts'
