version: '3.8'

services:
  sales-api:
    image: devopsdockerregistry.azurecr.io/salesapi:1.0.22
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - CONNECTIONSTRINGS__DATABASE=Server=db;Database=DevOpsChallenge.SalesApi;User=sales;Password=password123;
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - sales-network

  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    environment:
      SA_PASSWORD: "password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - sales-network
    volumes:
      - sqlvolume:/var/opt/mssql

networks:
  sales-network:
    driver: bridge

volumes:
  sqlvolume:
